apiVersion: v1
kind: Pod
metadata:
  labels:
    app: demo.82
  namespace: default
  name: web
spec:
  containers:
  - image: python-clean-architecture_web
    imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 0

#Generating kubernetes YAML file for the Service redis.yml
#This is Pod Configuration Kube definition
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: demo.91
  namespace: default
  name: redis.default
spec:
  containers:
  - image: redis:alpine
    imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 0

#Generating kubernetes YAML file for the Service nginx.yml
#This is Service Configuration Kube definition
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    generated.by: 8gwifi.org
  name: service.name.6
  namespace: default
spec:
  ports:
  - name: nameme_01
    port: 4000
    protocol: tcp
    targetPort: 4000
  selector:
    app: demo.57
  type: NodePort

#This is Pod Configuration Kube definition
---
kind: Pod
metadata:
  labels:
    app: demo.57
  namespace: default
spec:
  containers:
  - image: nginx:1.16
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 4000
      name: portname.0
      protocol: tcp
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf
      name: pvo.0
  terminationGracePeriodSeconds: 0
  volumes:
  - name: pvo.0
    persistentVolumeClaim:
      claimName: claimname.0

#This is PersistentVolume Kube Object with Name
#pvo.0.yml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    generated.by: 8gwifi.org
  name: pvo.0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /python-clean-architecture/nginx.conf
    type: Directory
  persistentVolumeReclaimPolicy: Retain

#This is PersistentVolumeClaim Kube Object with Name
#claimname.0.yml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    generated.by: 8gwifi.org
  name: claimname.0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvo.0